echo Starting JuFireX Backend and Frontend Services...
echo.

echo Starting Backend Flask Server (Port 5000)...
start "JuFireX Backend" cmd /k "cd /d f:\Code Projects\JuFireX && .venv\Scripts\activate && cd backend && python app.py"

echo Starting Frontend Dev Server (Port 8080)...
start "JuFireX Frontend" cmd /k "cd /d f:\Code Projects\JuFireX\frontend && npm run dev"

echo.
echo Services are starting...
echo Backend will be available at: http://localhost:5000
echo Frontend will be available at: http://localhost:5173
echo.
echo Press any key to close this window (this won't stop the services)...
pause > nul